{
 "title": "Anomaly Service Dashboard",
 "time": { "from": "2022-02-11T15:17:27.675Z", "to": "2022-02-11T15:41:55.860Z" },
 "panels": [
  {
   "title": "Endpoint usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(prediction_total[5m])", "legendFormat": "Prediction" },
    {
     "expr": "rate(model_information_total[5m])",
     "legendFormat": "Model information"
    }
   ]
  },
  {
   "title": "Predictions and scores",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(prediction_output_sum[120s])) / sum(increase(prediction_output_count[120s]))",
     "legendFormat": "Avg. prediction"
    },
    {
     "expr": "sum(increase(prediction_score_sum[120s])) / sum(increase(prediction_score_count[120s]))",
     "legendFormat": "Avg. score"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(latency_sum[120s])) / sum(increase(latency_count[120s]))",
     "legendFormat": "Latency"
    }
   ]
  }
 ]
}